// @ts-nocheck -- skip type checking
import * as docs_8 from "../content/docs/views/table.mdx?collection=docs&hash=1772034841722"
import * as docs_7 from "../content/docs/views/list.mdx?collection=docs&hash=1772034841722"
import * as docs_6 from "../content/docs/views/kanban.mdx?collection=docs&hash=1772034841722"
import * as docs_5 from "../content/docs/views/gallery.mdx?collection=docs&hash=1772034841722"
import * as docs_4 from "../content/docs/views/card.mdx?collection=docs&hash=1772034841722"
import * as docs_3 from "../content/docs/getting-started/quick-start.mdx?collection=docs&hash=1772034841722"
import * as docs_2 from "../content/docs/getting-started/installation.mdx?collection=docs&hash=1772034841722"
import * as docs_1 from "../content/docs/getting-started/column-definitions.mdx?collection=docs&hash=1772034841722"
import * as docs_0 from "../content/docs/index.mdx?collection=docs&hash=1772034841722"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"index.mdx","absolutePath":"/Users/mrbad/vibeprojects/eazytable/docs/content/docs/index.mdx"}, data: docs_0 }, { info: {"path":"getting-started/column-definitions.mdx","absolutePath":"/Users/mrbad/vibeprojects/eazytable/docs/content/docs/getting-started/column-definitions.mdx"}, data: docs_1 }, { info: {"path":"getting-started/installation.mdx","absolutePath":"/Users/mrbad/vibeprojects/eazytable/docs/content/docs/getting-started/installation.mdx"}, data: docs_2 }, { info: {"path":"getting-started/quick-start.mdx","absolutePath":"/Users/mrbad/vibeprojects/eazytable/docs/content/docs/getting-started/quick-start.mdx"}, data: docs_3 }, { info: {"path":"views/card.mdx","absolutePath":"/Users/mrbad/vibeprojects/eazytable/docs/content/docs/views/card.mdx"}, data: docs_4 }, { info: {"path":"views/gallery.mdx","absolutePath":"/Users/mrbad/vibeprojects/eazytable/docs/content/docs/views/gallery.mdx"}, data: docs_5 }, { info: {"path":"views/kanban.mdx","absolutePath":"/Users/mrbad/vibeprojects/eazytable/docs/content/docs/views/kanban.mdx"}, data: docs_6 }, { info: {"path":"views/list.mdx","absolutePath":"/Users/mrbad/vibeprojects/eazytable/docs/content/docs/views/list.mdx"}, data: docs_7 }, { info: {"path":"views/table.mdx","absolutePath":"/Users/mrbad/vibeprojects/eazytable/docs/content/docs/views/table.mdx"}, data: docs_8 }], [{"info":{"path":"meta.json","absolutePath":"/Users/mrbad/vibeprojects/eazytable/docs/content/docs/meta.json"},"data":{"title":"EazyTable","pages":["index","..."]}}, {"info":{"path":"getting-started/meta.json","absolutePath":"/Users/mrbad/vibeprojects/eazytable/docs/content/docs/getting-started/meta.json"},"data":{"title":"Getting Started","pages":["installation","quick-start","column-definitions"]}}, {"info":{"path":"views/meta.json","absolutePath":"/Users/mrbad/vibeprojects/eazytable/docs/content/docs/views/meta.json"},"data":{"title":"Views","pages":["table","card","list","kanban","gallery"]}}])